"""Add STT tables and models

Revision ID: 41f8fbb85bf9
Revises: 
Create Date: 2025-09-15 21:18:46.724457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41f8fbb85bf9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create STT tables only, do not modify existing tables
    op.create_table('stt_jobs',
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('source_uri', sa.String(length=512), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enable_diarization', sa.Boolean(), nullable=False),
    sa.Column('min_speakers', sa.Integer(), nullable=False),
    sa.Column('max_speakers', sa.Integer(), nullable=False),
    sa.Column('enable_word_time_offsets', sa.Boolean(), nullable=False),
    sa.Column('output_format', sa.String(length=10), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('storage_url', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_stt_jobs_status'), 'stt_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_stt_jobs_uuid'), 'stt_jobs', ['uuid'], unique=True)
    
    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('speaker', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_transcript_segments_job_id'), 'transcript_segments', ['job_id'], unique=False)
    op.create_index(op.f('ix_transcript_segments_uuid'), 'transcript_segments', ['uuid'], unique=True)
    
    op.create_table('word_timestamps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('speaker', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_word_timestamps_job_id'), 'word_timestamps', ['job_id'], unique=False)
    op.create_index(op.f('ix_word_timestamps_uuid'), 'word_timestamps', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop STT tables only
    op.drop_index(op.f('ix_word_timestamps_uuid'), table_name='word_timestamps')
    op.drop_index(op.f('ix_word_timestamps_job_id'), table_name='word_timestamps')
    op.drop_table('word_timestamps')
    op.drop_index(op.f('ix_transcript_segments_uuid'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_job_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_stt_jobs_uuid'), table_name='stt_jobs')
    op.drop_index(op.f('ix_stt_jobs_status'), table_name='stt_jobs')
    op.drop_table('stt_jobs')
    # ### end Alembic commands ###
